"""AI assistant with document search (Gemini File Search)

Chat with a set of PDF documents: they are indexed in a Google Gemini File
Search store, and each question is answered by Gemini using passages retrieved
from them, with the source documents and pages cited below the answer.

Documents can be indexed at startup from a folder (``--docs-dir``), or at any
time by attaching them to a chat message. The store persists on Google's side,
so documents only need to be indexed once.

Requires ``pip install google-genai`` and a ``GEMINI_API_KEY`` environment
variable.

* :meth:`viser.GuiApi.add_chat` for the chat, inside a panel tab
* :class:`viser.extras.GeminiFileSearch` to index documents and answer from them
"""

from __future__ import annotations

import time
from pathlib import Path

import tyro

import viser
from viser.extras import GeminiFileSearch


def main(
    docs_dir: Path | None = None,
    store: str = "viser-studio-docs",
    model: str = "gemini-3.8-flash",
) -> None:
    """Start the assistant.

    Args:
        docs_dir: Folder of documents to index at startup (already-indexed
            files are skipped).
        store: Display name of the File Search store; created if missing.
        model: Gemini model to answer with. Must support File Search.
    """
    rag = GeminiFileSearch(store, model=model)
    if docs_dir is not None:
        for name in rag.index_folder(docs_dir):
            print(f"Indexed {name}")

    server = viser.ViserServer()
    panel = server.gui.add_panel()
    chat = server.gui.add_chat(
        "Document Assistant",
        parent=panel.add_tab("Assistant", viser.Icon.MESSAGE_CHATBOT),
        greeting="Hi there!",
        subtitle="Ask me anything about your documents.",
        suggestions=("Summarize the documents", "What topics do they cover?"),
        disclaimer=(
            "Answers are generated by Gemini from the indexed documents. Always "
            "check the cited sources."
        ),
        placeholder="Ask about your documents…",
        store=viser.ConversationStore(Path.home() / ".viser" / "rag_chat_history"),
    )
    with panel.add_tab("Documents", viser.Icon.FILES):
        document_list = server.gui.add_markdown("")
    rag.connect(chat, document_list=document_list)

    print(f"File Search store: {rag.store_name} ({len(rag.documents())} documents)")
    while True:
        time.sleep(10.0)


if __name__ == "__main__":
    tyro.cli(main)
